export const defaultPeople = [
  { name: 'Adam Blank', responded: false },
  { name: 'Adam Ramos', responded: false },
  { name: 'Ari Spivack', responded: false },
  { name: 'Amira Herstic', responded: false },
  { name: 'Andrew Botvinik', responded: false },
  { name: 'Arny Bal', responded: false },
  { name: 'Ben Kohane', responded: false },
  { name: 'Ben Strachman', responded: false },
  { name: 'Daniel Blau', responded: false },
  { name: 'Dina Margelovich', responded: false },
  { name: 'Doni Goldstien', responded: false },
  { name: 'Dror Galili', responded: false },
  { name: 'Jason Weiss', responded: false },
  { name: 'Jay Berman', responded: false },
  { name: 'Jeremy Tuch', responded: false },
  { name: 'Joey Silverstein', responded: false },
  { name: 'Josh Tepper', responded: false },
  { name: 'Meir Spector', responded: false },
  { name: 'Michael Bernstein', responded: false },
  { name: 'Michael Schwartz', responded: false },
  { name: 'Michael Shapiro', responded: false },
  { name: 'Rafe', responded: false },
  { name: 'Rafi Strauss', responded: false },
  { name: 'Shneur Kovacs', responded: false },
  { name: 'Uri Strauss', responded: false },
  { name: 'Yehonatan Haimovici', responded: false },
  { name: 'Yoel Gerstein', responded: false },
  { name: 'Yoni Block', responded: false },
  { name: 'Yoni Friedman', responded: false },
  { name: 'Zev Newman', responded: false },
  { name: 'Zvi Wiesenfeld', responded: false },
  { name: "Ariel Schabes", responded: false },
  { name: "Max Kimmel", responded: false },
].sort((a, b) => a.name.localeCompare(b.name));